const ScreenNames = {
  //HOME
  HOME: 'HOME',
  HOME_1: 'HOME_1',
  HOME_2: 'HOME_2',
  HOME_ROUTE: 'HOME_ROUTE',
  HOME_NAVIGATOR: 'HOME_NAVIGATOR',
  HOME_CAMPAIGN: 'HOME_CAMPAIGN',
  HOME_ACTIVITY: 'HOME_ACTIVITY',
  HOME_BLOG: 'HOME_BLOG',

  //LOGIN
  LOGIN: 'LOGIN',
  LOGIN_NAVIGATOR: 'LOGIN_NAVIGATOR',
  WITH_BACKGROUND_LOGIN: 'WITH_BACKGROUND_LOGIN',
  WITH_LOGO_LOGIN: 'WITH_LOGO_LOGIN',
  WITH_PROFILE_IMAGE_LOGIN: 'WITH_PROFILE_IMAGE_LOGIN',
  WITH_BACKGROUND_REGISTER: 'WITH_BACKGROUND_REGISTER',
  WITH_LOGO_REGISTER: 'WITH_LOGO_REGISTER',
  WITH_PROFILE_IMAGE_REGISTER: 'WITH_PROFILE_IMAGE_REGISTER',
  WITH_BACKGROUND_SEND_CONFIRMATION: 'WITH_BACKGROUND_SEND_CONFIRMATION',
  WITH_BACKGROUND_ENTER_CONFIRMATION: 'WITH_BACKGROUND_ENTER_CONFIRMATION',
  WITH_LOGO_SEND_CONFIRMATION: 'WITH_LOGO_SEND_CONFIRMATION',
  WITH_LOGO_ENTER_CONFIRMATION: 'WITH_LOGO_ENTER_CONFIRMATION',
  WITH_PROFILE_IMAGE_SEND_CONFIRMATION: 'WITH_PROFILE_IMAGE_SEND_CONFIRMATION',
  WITH_PROFILE_IMAGE_ENTER_CONFIRMATION:
    'WITH_PROFILE_IMAGE_ENTER_CONFIRMATION',
};

export default ScreenNames;
