const ScreenNames = {
  HOME: 'HOME',
  HOME_NAVIGATOR: 'HOME_NAVIGATOR',
  LOGIN: 'LOGIN',
  LOGIN_NAVIGATOR: 'LOGIN_NAVIGATOR',
  WITH_BACKGROUND: 'WITH_BACKGROUND',
  WITH_LOGO: 'WITH_LOGO',
  WITH_PROFILE_IMAGE: 'WITH_PROFILE_IMAGE',
};

export default ScreenNames;
