const ScreenNames = {
  HOME: 'HOME',
  HOME_NAVIGATOR: 'HOME_NAVIGATOR',
  LOGIN: 'LOGIN',
  LOGIN_NAVIGATOR: 'LOGIN_NAVIGATOR',
  WITH_BACKGROUND_LOGIN: 'WITH_BACKGROUND_LOGIN',
  WITH_LOGO_LOGIN: 'WITH_LOGO_LOGIN',
  WITH_PROFILE_IMAGE_LOGIN: 'WITH_PROFILE_IMAGE_LOGIN',
  WITH_BACKGROUND_REGISTER: 'WITH_BACKGROUND_REGISTER',
  WITH_LOGO_REGISTER: 'WITH_LOGO_REGISTER',
  WITH_PROFILE_IMAGE_REGISTER: 'WITH_PROFILE_IMAGE_REGISTER',
  WITH_BACKGROUND_SEND_CONFIRMATION: 'WITH_BACKGROUND_CONFIRMATION',
  WITH_LOGO_SEND_CONFIRMATION: 'WITH_LOGO_SEND_CONFIRMATION',
  WITH_PROFILE_IMAGE_SEND_CONFIRMATION: 'WITH_PROFILE_IMAGE_SEND_CONFIRMATION',
};

export default ScreenNames;
